version: '3'
services:
  galleryweb:
    build: 
      context: ./
      dockerfile: node.DOCKERFILE
    user: node
    working_dir: /home/node/app
    command: ["sh", "-c", "npm install && npm start"]
    volumes:
      - ./:/home/node/app/:ro
      - /home/node/app/node_modules/
    ports:
      - "127.0.0.1:3000:3000"